services:
  # Base de données MariaDB
  mariadb:
    image: mariadb:latest
    container_name: yomikai-db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - yomikai_network
    restart: unless-stopped

  # Application Next.js
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DATABASE_URL: mysql://${DB_USER}:${DB_PASSWORD}@mariadb:3306/${DB_NAME}
        NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
        NEXTAUTH_URL: ${NEXTAUTH_URL}
    container_name: yomikai-app
    environment:
      - NODE_ENV=production
      - DATABASE_URL=mysql://${DB_USER}:${DB_PASSWORD}@mariadb:3306/${DB_NAME}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
    ports:
      - "3000:3000"
    volumes:
      # Volume pour les uploads d'images
      - uploads_data:/app/public/uploads
    networks:
      - yomikai_network
    depends_on:
      - mariadb
    restart: unless-stopped

volumes:
  mariadb_data:
  uploads_data:

networks:
  yomikai_network:
    driver: bridge