version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: yomikai
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-1234}
      MYSQL_DATABASE: ${DB_NAME:-yomikai}
      MYSQL_USER: ${DB_USER:-yomikai}
      MYSQL_PASSWORD: ${DB_PASSWORD:-1234}
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - lol_network

volumes:
  mariadb_data:

networks:
  lol_network:
    driver: bridge